#ifndef STAGE_MACRO_DEFINED_
#define STAGE_MACRO_DEFINED_

// CORS
#define CORS_ALLOW_ORIGIN "*"
#define CORS_ALLOW_METHODS "GET,POST,PATCH,DELETE,OPTIONS"
#define CORS_ALLOW_HEADERS "*"
#define CORS_EXPOSE_HEADERS "*"
#define CORS_ALLOW_CREDENTIALS "*"
#define CORS_MAX_AGE 86400
#endif
