AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cpp-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  CppSamplesGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/CppSamplesGet/build/handler.zip
      Handler: handler
      PackageType: Zip
      Runtime: provided
      MemorySize: 512
      Events:
        CppSamplesGet:
          Type: Api
          Properties:
            Path: /cpp-sample-get
            Method: get
      AutoPublishAlias: dev
      FunctionName: 'cpp-sample-get'
      # Role: 'arn:aws:iam::xxxxxxxxxxxx:role/FullAccess'
      # DeploymentPreference:
      #     Type: Linear10PercentEvery1Minute
    Metadata:
      # BuildMethod: makefile
  # CppSamplesPost:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: ./src/CppSamplesPost/build/handler.zip
  #     Handler: handler
  #     PackageType: Zip
  #     Runtime: provided
  #     MemorySize: 512
  #     Events:
  #       CppSamplesPost:
  #         Type: Api
  #         Properties:
  #           Path: /cpp-sample-post
  #           Method: post
  #   Metadata:
  #     # BuildMethod: makefile

Outputs:
  CppSamplesGet:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cpp-sample-get/"
    

